builds:
  - binary: ezcert
    main: ./cmd/ezcert.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64

archive:
  replacements:
    amd64: 64-bit
    darwin: macOS
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - docs/*

changelog:
  exclude:
    - '^ci:'
    - '^typo:'