# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/itzg/ezcert
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make test
      - run: make snapshot

      - store_artifacts:
          path: dist
          destination: dist

      - run:
          name: gorelease, if tag
          command: |
            if [[ -v GITHUB_TOKEN && -v CIRCLE_TAG ]]; then
              make release
            fi

  release:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/itzg/ezcert
    steps:
      - checkout

      - run: make release

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              ignore: /\d+\.\d+\.\d+/
      - release:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/